function E = corrected_element_data()
% CORRECTED_ELEMENT_DATA
% Explicit element records for a periodic-table visualization.
% Atomic numbers are stored directly and must never be generated from
% displayed table position because the f-block is visually detached.

E = struct('Z', {}, 'symbol', {}, 'row', {}, ...
           'col', {}, 'block', {}, 'series', {});

% Period 1
E = add_elements(E, 1, {'H','He'}, ...
    [1,18], [1,2]);

% Period 2
E = add_elements(E, 2, ...
    {'Li','Be','B','C','N','O','F','Ne'}, ...
    [1,2,13,14,15,16,17,18], ...
    [3,4,5,6,7,8,9,10]);

% Period 3
E = add_elements(E, 3, ...
    {'Na','Mg','Al','Si','P','S','Cl','Ar'}, ...
    [1,2,13,14,15,16,17,18], ...
    [11,12,13,14,15,16,17,18]);

% Period 4
E = add_elements(E, 4, ...
    {'K','Ca','Sc','Ti','V','Cr','Mn','Fe','Co', ...
     'Ni','Cu','Zn','Ga','Ge','As','Se','Br','Kr'}, ...
    1:18, 19:36);

% Period 5
E = add_elements(E, 5, ...
    {'Rb','Sr','Y','Zr','Nb','Mo','Tc','Ru','Rh', ...
     'Pd','Ag','Cd','In','Sn','Sb','Te','I','Xe'}, ...
    1:18, 37:54);

% Period 6 main table.
% The lanthanides Ce–Lu, Z = 58–71, are shown separately.
E = add_elements(E, 6, ...
    {'Cs','Ba','La','Hf','Ta','W','Re','Os','Ir', ...
     'Pt','Au','Hg','Tl','Pb','Bi','Po','At','Rn'}, ...
    1:18, ...
    [55,56,57,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86]);

% Period 7 main table.
% The actinides Th–Lr, Z = 90–103, are shown separately.
E = add_elements(E, 7, ...
    {'Fr','Ra','Ac','Rf','Db','Sg','Bh','Hs','Mt', ...
     'Ds','Rg','Cn','Nh','Fl','Mc','Lv','Ts','Og'}, ...
    1:18, ...
    [87,88,89,104,105,106,107,108,109,110,111,112, ...
     113,114,115,116,117,118]);

% Displayed lanthanide row.
E = add_elements(E, 8, ...
    {'Ce','Pr','Nd','Pm','Sm','Eu','Gd','Tb','Dy', ...
     'Ho','Er','Tm','Yb','Lu'}, ...
    4:17, 58:71);

% Displayed actinide row.
E = add_elements(E, 9, ...
    {'Th','Pa','U','Np','Pu','Am','Cm','Bk','Cf', ...
     'Es','Fm','Md','No','Lr'}, ...
    4:17, 90:103);

for k = 1:numel(E)
    E(k).block = block_from_position(E(k));
    E(k).series = series_from_position(E(k));
end
end

function E = add_elements(E, row, symbols, cols, atomicNumbers)

assert(numel(symbols) == numel(cols), ...
    'symbols and cols must have equal lengths.');

assert(numel(symbols) == numel(atomicNumbers), ...
    'symbols and atomicNumbers must have equal lengths.');

for k = 1:numel(symbols)
    E(end+1) = struct( ...
        'Z', atomicNumbers(k), ...
        'symbol', symbols{k}, ...
        'row', row, ...
        'col', cols(k), ...
        'block', '', ...
        'series', ''); %#ok<AGROW>
end
end

function block = block_from_position(e)

if e.row == 8 || e.row == 9
    block = 'f';
elseif e.col <= 2
    block = 's';
elseif e.col >= 13
    block = 'p';
else
    block = 'd';
end

if strcmp(e.symbol, 'He')
    block = 's';
end
end

function series = series_from_position(e)

if e.row == 8
    series = 'lanthanide';
elseif e.row == 9
    series = 'actinide';
elseif strcmp(e.block, 'd')
    series = 'transition metal';
else
    series = 'main group';
end
end